In [1]:
!pip install nltk

In [2]:
text = ["This is a line",
       "This is another line",
       "Completely different line"]

### CountVectorizer

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
# help(CountVectorizer)

In [5]:
cv = CountVectorizer()

In [6]:
sparse_matrix = cv.fit_transform(text)

In [7]:
sparse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [8]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

### TF-IDF Vectorizer

In [9]:
from sklearn.feature_extraction.text import TfidfTransformer

In [10]:
tfidf = TfidfTransformer()

In [11]:
sparse_matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [12]:
results = tfidf.fit_transform(sparse_matrix) #BOW ---> TF-IDF

In [13]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [15]:
tv = TfidfVectorizer()

In [16]:
tv_results = tv.fit_transform(text)

In [17]:
tv_results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])